name = "kinsen-station-ai"
pages_build_output_dir = "dist"
compatibility_date = "2024-06-20"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "bd331e128b6a455a961b5a9aa939a8c7"
preview_id = "8fb3afe1db404547b47c9511ce935508"
