name = "kinsen-station-ai"
pages_build_output_dir = "dist"
compatibility_date = "2026-02-27"

[ai]
binding = "AI"

[env.production]
compatibility_date = "2024-06-20"

[env.production.vars]
PIN_SALT_SECRET = "change-me-in-production"

[[env.production.kv_namespaces]]
id = "bd331e128b6a455a961b5a9aa939a8c7"
binding = "KV"
